#!/usr/bin/env bash
set -ex

pwd

project='kochiku-worker'

mv config/kochiku-worker.prod-dc.yml config/kochiku-worker.yml

# download and run hoist-buildpack
rm -Rf /tmp/buildpack
git clone git://git-mirror.corp.squareup.com/sq/hoist-buildpacks.git /tmp/buildpack --branch green --depth 1 --quiet
/tmp/buildpack/bin/hoist-mri $project --bare-ruby --ruby 2.3 --cache-bundle --no-assets --no-mysql-client --stunnel
