#!/usr/bin/env bash
set -ex

logstreamer_sha='3c56074dfa0d76fb07cf09a50b13ff566d376a1f'
pushd /project/logstreamer
curl -LsS https://hoistrepo-api.vip/download/user-submitted-artifacts/logstreamer/logstreamer_${logstreamer_sha}.tar.gz | tar -zxf -
popd

# Set the version of git you want here, based on git-partial project sha
# https://stash.corp.squareup.com/projects/CII/repos/git-partial/browse
git_partial_sha=6c6b64ab8baef766e148e1f0e7130bc34679ca23
curl -LsS https://hoistrepo-api.vip/download/partial-artifact/git-partial/git-partial_${git_partial_sha}.tar.gz | tar -zx

# Copy in the Java JDK for Android
# unpacks into java/jdk${java_version}
java_version='1.8.0_121'
curl -LsS https://hoistrepo-api.vip/download/build-artifact/jdk-${java_version}.tar.gz \
    | tar --strip-components=2 -zxf - ./usr/java/
