#!/usr/bin/env bash

echo Command: $0 $*
echo
echo "Environment:"
hostname
env
echo

# set -ex: make script verbose and exit on first failed command
set -ex

RUN_LIST=$(echo $RUN_LIST | tr "," " ")

gem install bundler -v '~> 1.5' --conservative
if [[ -n $KOCHIKU_ENV ]]; then
    bundle_install_from_shared_cache kochiku-worker
else
    bundle check || bundle install
fi
bundle exec rspec $RUN_LIST
